### PR TITLE
Add data card guide and template

### PR DESCRIPTION
**Pull request by sebastianGehrmann**

### CODE REVIEW

**Comment by sebastianGehrmann** [comment]
I added an initial version of a restructured data card. Please have a look.

**Comment by yjernite** [comment]
I like the "Impact on Underserved Communities" title.

LGTM!

(are the js and css file changes intentional or di they get inherited from another branch?)

**Review by juand-r — APPROVED** [review]
The template and guide look good to me!

**Comment by sebastianGehrmann** [comment]
The js and css changes are for linking and rendering the guide on the website. Thanks for taking a look. If there are no other comments, I will merge tomorrow.

**Review by Shashi456 — APPROVED** [review]
LGTM

Just a question, I think we had mentioned that we might want to add a section for the baseline models/research for each of these datasets?

**Comment by juand-r** [comment]
> LGTM
> 
> Just a question, I think we had mentioned that we might want to add a section for the baseline models/research for each of these datasets?

I think that is covered in "Getting started with in-depth research on the task".

**Comment by sebastianGehrmann** [comment]
Indeed, this is what that section is for. I am going to merge this now, but feel free to edit and submit updating PRs - I won't distribute the template/guide until our examples are updated :)

**Pull request merged**
