### PR TITLE
Add leaderboard page

### PR DESCRIPTION
**Pull request by madaan**
Adds a leaderboard page for the website.

The current implementation essentially renders the results from a leaderboard.csv file using a data table.

### CODE REVIEW

**Review by sebastianGehrmann — COMMENTED** [review]
Looking good for a first step! Could you sync to head so that the navbar changes are not being reverted? 

Also, what is your idea for tasks with non-overlapping metrics? Are they still going to be in the same table? And does it make sense to use a csv when the metrics script output is one json per model/dataset? We should probably add a formatter for this.

**Comment by madaan** [comment]
Synced! Yeah I think the output format should not be a big problem. As you mention, we can write appropriate formatters. I'll give some more thought to the design of the table(s) to accommodate multiple tasks/metrics and will reach out to you with some ideas by the weekend.

**Comment by sebastianGehrmann** [comment]
Thanks for the updates! 

Two small changes and v0 is ready to be merged: 

1) Could you rename `leaderboard` into result table or so, I really don't want the results to be confused with one :) 
2) Can you change the data loading to the format I sent via email. That would make the pipeline much easier since we wouldn't have to reformat everything every time a model comes in.

**Comment by madaan** [comment]
Thanks, those are easy fixes once I understand the format of metrics_*.json

If I understand it right, each metrics file has the following structure:

```js
{
  "task1": {
        "metrics_a": ""
  },
  "task2": {
        "metrics_a": ""
  },
 .
.
.
}
```

Example:

image

Is that correct?

A couple of things need to be finalized:

a) Task abbreviations: Have the task abbreviations been standardized yet?  I see that the task keys are currently formatted roughly as `taskname_*_split` but it would be useful to standardize this.

b) Metrics to display: The metrics file currently contain a lot of different metrics, and we don't want to/can't display all of them (at least by default). Perhaps we can decide on the primary metrics for each task?

**Comment by sebastianGehrmann** [comment]
Yes, this is the format of the metrics file(s). 

Regarding (a) - We will do this when we have the final test sets. For now, I think it is fine to just display the split names as `taskname_split` and we can fix this later. 

Regarding (b) We want to be able to display all of them, but maybe aggregate in some ways (like all the diversity metrics can be unified in some way, for example). This is something where @HendrikStrobelt has more expertise than me. For now, maybe just display all of them since we are going to change the display method anyway?

**Comment by madaan** [comment]
Hey Sebastian,

These changes are done now. The metrics files that you shared are directly consumed by the [lib/results.js](https://github.com/GEM-benchmark/GEM-benchmark.github.io/blob/leaderboard/web/lib/results.js). The details of the current workflow are [here](https://github.com/GEM-benchmark/GEM-benchmark.github.io/blob/leaderboard/web/results/README.md).

**Comment by sebastianGehrmann** [comment]
Thanks for writing the documentation for the workflow, this is a great start. I'll merge this for now!

**Pull request merged**
